CREATE TABLE IF NOT EXISTS `Comment` 
( 
	ID INT NOT NULL AUTO_INCREMENT,
	UserComment VARCHAR(500) NOT NULL,
	PostID INT(11) NOT NULL, 
	StudentID INT(11) NOT NULL,
	CONSTRAINT PF_CSInvestment_Comment
		PRIMARY KEY (ID),
	CONSTRAINT FK_Comment_Post
		FOREIGN KEY (PostID)
		REFERENCES Post(ID),
	CONSTRAINT FK_Comment_Student
		FOREIGN KEY (StudentID)
		REFERENCES Student(ID)
);